class_names: ["oneway", "highwayentrance", "stopsign", "roundabout", "park", "crosswalk", "noentry", "highwayexit", "priority", "lights", "block", "pedestrian", "car"]
<<<<<<< HEAD
confidence_thresholds: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.85, 0.9]
max_distance_thresholds: [1.0, 1.5, 2.0, 2.0, 2.4, 1.5, 1.0, 0.9, 1.5, 1.5, 1.5, 1., 1.4]
=======
# ["person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light",
# "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
# "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
# "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard",
# "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
# "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
# "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone",
# "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
# "hair drier", "toothbrush"
# ]
# confidence_thresholds: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,]
# max_distance_thresholds: [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,
# 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,]
confidence_thresholds: [0.8, 0.8, 0.8, 0.8, 0.5, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.9]
max_distance_thresholds: [1.0, 2.0, 2.0, 2.0, 2.4, 2.0, 2.0, 0.9, 2.0, 2.0, 2.0, 1., 0.9]
>>>>>>> origin/main
model: "sissi753-opt"
